apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "tyk-sre-assignment.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "tyk-sre-assignment.labels" . | nindent 4 }}